version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: smart
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  meilisearch:
    image: getmeili/meilisearch:v1.1.1
    environment:
      MEILI_MASTER_KEY: masterKey
    ports:
      - '7700:7700'
    volumes:
      - meili_data:/data.ms

volumes:
  pgdata:
  meili_data:
