name: CI — build & test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install root deps
        run: npm ci

      - name: Bootstrap (install and build backend+frontend)
        run: npm run bootstrap

      - name: Run tests for backend and frontend
        run: npm run test:all
        env:
          CI: true

      - name: Upload frontend build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: smart-market-finder-1/frontend/build
